//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObservableVariablesTest.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariablesValuesSet
    {
        public int Id { get; set; }
        public int idData { get; set; }
        public string ValueSender { get; set; }
        public string ValueArgs { get; set; }
    }
}
