// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18444
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace RestaurantApp.Voting.AcceptanceTests.UserStories
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class Estoria3_MostrarDeAlgumaFormaOResultadoDaVotacao_Feature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Estoria-3 Permitir a Consulta do Restaurante Escolhido.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Estória 3 - Mostrar de alguma forma o resultado da votação.", "  Eu como profissional faminto\r\n  Quero saber antes do meio dia qual foi o restau" +
                    "rante escolhido\r\n  Para que eu possa me despir de preconceitos e preparar o psic" +
                    "ológico.", ProgrammingLanguage.CSharp, new string[] {
                        "requires_database"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "Estória 3 - Mostrar de alguma forma o resultado da votação.")))
            {
                RestaurantApp.Voting.AcceptanceTests.UserStories.Estoria3_MostrarDeAlgumaFormaOResultadoDaVotacao_Feature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
#line 8
        testRunner.Given("os seguintes profissionais: Bruno, Kauã, Maicon, Brian, Matheus, Tiago", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dados ");
#line 9
        testRunner.And("os seguintes restaurantes: Piazza, Pinguin, Banquette, Speedy", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Caso houver empate, Os mais votados deveriam ser retornados como os escolhidos.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Estória 3 - Mostrar de alguma forma o resultado da votação.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("requires_database")]
        public virtual void CasoHouverEmpateOsMaisVotadosDeveriamSerRetornadosComoOsEscolhidos_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Caso houver empate, Os mais votados deveriam ser retornados como os escolhidos.", ((string[])(null)));
#line 11
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line 12
        testRunner.Given("que o \'Matheus\' votou no restaurante \'Speedy\' \'hoje\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 13
        testRunner.Then("o restaurante mais votado no momento deveria ser: Speedy", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line 14
        testRunner.Given("que \'Bruno, Kauã\' votaram no restaurante \'Piazza\' \'hoje\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 15
        testRunner.Then("o restaurante mais votado no momento deveria ser: Piazza", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line 16
        testRunner.Given("que \'Maicon, Brian\' votaram no restaurante \'Banquette\' \'hoje\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 17
        testRunner.Then("os restaurantes mais votados no momento deveriam ser: Piazza, Banquette", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line 18
        testRunner.Given("que o \'Tiago\' votou no restaurante \'Piazza\' \'hoje\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 19
        testRunner.Then("os restaurantes mais votados deveriam ser: Piazza", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
